name: Publish Extension

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run compile
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCODE_MARKET_PLACE_ACCESS_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCODE_MARKET_PLACE_ACCESS_TOKEN }}