name: Release (Minor)

on:
  workflow_dispatch: {}

jobs:
  release:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/_release-common.yaml
    with:
      bump: minor
    secrets: inherit
